CREATE 
(python:Subject {name:'Python'}),
(java:Subject {name:'Java'}),
(advanced_python:Subject {name:'Advanced Python'}),
(design_patterns:Subject {name:'Design Patterns'}),
(database:Subject {name:'Database'}),
(ruby:Subject {name:'Ruby'}),
(c_sharp:Subject {name:'C##'}),
(swift:Subject {name:'Swift'}),
(android:Subject {name:'Android'}),
(cplus:Subject {name:'C++'}),
(javascript:Subject {name:'Javascript'}),
(testing:Subject {name:'Testing'}),

(kea:Department {name: 'KEA Department'}),

(sd22spr: Semester {name: 'SD22 Spring'}),
(sd22sum: Semester {name: 'SD22 Summer'}),

(tomas:Teacher {name: 'Tomas',email:'tomas@kea.dk'}),
(jarl:Teacher {name: 'Jarl',email:'jarl@kea.dk'}),
(asger:Teacher {name: 'Asger',email:'asbc@kea.dk'}),
(andrea:Teacher {name: 'Andrea',email:'ande@kea.dk'}),

(database)-[:TAUGHT_IN]->(sd22spr),
(python)-[:TAUGHT_IN]->(sd22spr),
(java)-[:TAUGHT_IN]->(sd22spr),
(advanced_python)-[:TAUGHT_IN]->(sd22spr),
(design_patterns)-[:TAUGHT_IN]->(sd22spr),
(ruby)-[:TAUGHT_IN]->(sd22spr),
(c_sharp)-[:TAUGHT_IN]->(sd22sum),
(swift)-[:TAUGHT_IN]->(sd22sum),
(android)-[:TAUGHT_IN]->(sd22sum),
(cplus)-[:TAUGHT_IN]->(sd22sum),
(javascript)-[:TAUGHT_IN]->(sd22sum),
(testing)-[:TAUGHT_IN]->(sd22sum),

(tomas)-[:TEACHES]->(database),
(tomas)-[:TEACHES]->(python),
(tomas)-[:TEACHES]->(java),
(jarl)-[:TEACHES]->(advanced_python),
(jarl)-[:TEACHES]->(design_patterns),
(jarl)-[:TEACHES]->(c_sharp),
(asger)-[:TEACHES]->(swift),
(asger)-[:TEACHES]->(ruby),
(asger)-[:TEACHES]->(android),
(andrea)-[:TEACHES]->(cplus),
(andrea)-[:TEACHES]->(javascript),
(andrea)-[:TEACHES]->(testing),

(tomas)-[:BELONGS_TO]->(kea),
(jarl)-[:BELONGS_TO]->(kea),
(asger)-[:BELONGS_TO]->(kea),
(andrea)-[:BELONGS_TO]->(kea)

