-- DELETE ALL CODES ONCE A DAY --

DROP EVENT IF EXISTS deleteCodesDaily;

CREATE EVENT deleteCodesDaily
ON SCHEDULE EVERY 1 DAY 
START CURRENT_TIMESTAMP + INTERVAL 1 DAY
DO DELETE * FROM `rollcall_db`.`code`;