version: "3.1"

services:

  mysql_container:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      # here you set the root user's password for the new database
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQLDB_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_TCP_PORT: ${MYSQLDB_DOCKER_PORT}
    volumes:
      - sqldb:/var/lib/mysql
      # this mounts the repo's ./sql directory to the container's init directory
      # search for docker-entrypoint-initdb in the docs: https://hub.docker.com/_/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
volumes:
  sqldb: