version: "3.1"

services:
  #  app_container:

  mysql_container:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      # here you set the root user's password for the new database
      MYSQL_ROOT_PASSWORD: databases
    volumes:
      - sqldb:/var/lib/mysql
      # this mounts the repo's ./sql directory to the container's init directory
      # the scripts will run only when the volume is removed with docker-compose down -v
      # search for docker-entrypoint-initdb in the docs: https://hub.docker.com/_/mysql
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  sqldb:
