
GET http://localhost:8080/sql/teachers/all
Content-Type: application/json

###
POST http://localhost:8080/sql/teachers/createNew
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doeh",
    "email": "sage@test.com",
    "password": "12345678",
    "department_id": 2
}

###
GET http://localhost:8080/sql/teachers/findOne/2
Content-Type: application/json

###
POST http://localhost:8080/sql/teachers/updateOne/2
Content-Type: application/json

{
    "first_name": "Michael",
    "last_name": "Doeh",
    "email": "sage@test.com",
    "password": "12345678",
    "department_id": "2"
}

###
POST http://localhost:8080/sql/teachers/delete/3
Content-Type: application/json

