### Login Teacher
POST http://localhost:8080/sql/login/
Content-Type: application/json

{
    "email": "ASBC@kea.dk", 
    "password": "weqweqwe"

}

### Login Student
POST http://localhost:8080/sql/login/
Content-Type: application/json

{
    "email": "Ole1234@kea.dk", 
    "password": "weqweqwe"

}

###

GET http://localhost:8080/sql/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlQHRlc3QuY29tIiwiaWQiOjYsImlhdCI6MTYzNzc3NDgzM30.rcLtRIh9K4zscB8Sw38fsk5buNVuFYfRWxjY7soxHyg
