### Login Teacher
POST http://localhost:8080/sql/login/
Content-Type: application/json

{
    "email": "ASBC@kea.dk", 
    "password": "weqweqwe"

}

### Login Student
POST http://localhost:8080/sql/login/
Content-Type: application/json

{
    "email": "Ole1234@kea.dk", 
    "password": "weqweqwe"

}

###

GET http://localhost:8080/sql/auth/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVhY2hlciIsImVtYWlsIjoiQVNCQ0BrZWEuZGsiLCJpZCI6MSwiaWF0IjoxNjQzNDU3MDQ2fQ.kjLkG0mVS8i1UzVhbcX2fD7ovRi9ZquIVuTLZRgXVmc

###
GET http://localhost:8080/sql/logout/