### Login Teacher
POST http://localhost:8080/sql/login/
Content-Type: application/json

{
    "email": "ASBC@kea.dk", 
    "password": "weqweqwe"

}

### Login Student
POST http://localhost:8080/sql/login/
Content-Type: application/json

{
    "email": "Ole1234@kea.dk", 
    "password": "weqweqwe"

}

###

GET http://localhost:8080/sql/auth/
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik9sZTEyMzRAa2VhLmRrIiwiaWQiOjEsImlhdCI6MTY0MzQ1MzQyNX0.Q0QSaMnOye_88DM267ij3tfJTEK6Y9UlwWd2RH3ypQo