GET http://localhost:8080/auth-test

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTYzNjU3MDA2M30.6MDl9bTlrqptirS-QcrliizVs697mB-qc94IIbbznmM