###POST 
POST http://localhost:8080/register/ 
Content-Type: application/json

{
    "first_name": "name",
    "last_name": "names",
    "email": "reste@test.com",
    "password": "qweqwe",
    "department_id": 3
}

###GET

GET http://localhost:8080/login/
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "qweqwe"
}


