###POST 
POST http://localhost:8080/sql/register/ 
Content-Type: application/json

{
    "first_name": "lars",
    "last_name": "names",
    "email": "teste@test.com",
    "password": "qweqweqwe",
    "department_id": 3
}

###GET
